# Dependency Review — gates PRs that introduce vulnerable or
# disallowed-license dependencies. Public repos: free.
# Private repos: requires GitHub Advanced Security.
# See: https://github.com/actions/dependency-review-action
name: dependency review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # ratchet:actions/dependency-review-action@v5
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: on-failure
